apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - flux-system
  - ../../infrastructure/metallb
  - ../../infrastructure/monitoring
  - ../../infrastructure/nginx-ingress
  - ../../infrastructure/cert-manager
  - ../../apps/smoke-test
  - ../../apps/homepage
  - ../../apps/storage-test
