apiVersion: v1
kind: Service
metadata:
  name: nginx-smoke-test
  namespace: smoke-test
  labels:
    app.kubernetes.io/name: nginx-smoke-test
    app.kubernetes.io/part-of: homelab
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nginx-smoke-test
  ports:
    - name: http
      port: 80
      targetPort: http
