---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - flux-system
  - ../../environments/staging/metallb
  - ../../environments/staging/nginx-ingress
  - ../../environments/staging/smoke-test
