apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mongodb-data
  namespace: rocketchat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi #8 Gigabytes for chat logs

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocketchat-uploads
  namespace: rocketchat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi #10 Gigabytes for uploaded pictures/files
      

