apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocketchat-uploads
  namespace: rocketchat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rocketchat-app
  namespace: rocketchat
spec:
  ports:
    - port: 3000
  selector:
    app: rocketchat-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketchat-app
  namespace: rocketchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketchat-app
  template:
    metadata:
      labels:
        app: rocketchat-app
    spec:
      containers:
        - name: rocketchat
          image: registry.rocket.chat/rocketchat/rocket.chat:latest
          env:
            - name: PORT
              value: "3000"
            - name: ROOT_URL
              value: "https://chat.dev-andrew.com"
            - name: SECRET_PASS
              valueFrom:
                secretKeyRef:
                  name: rocketchat-db-secret
                  key: mongo-root-password
            - name: MONGO_URL
              value: "mongodb://root:$(SECRET_PASS)@rocketchat-mongo-0.rocketchat-mongo:27017/rocketchat?replicaSet=rs0&authSource=admin"
            - name: MONGO_OPLOG_URL
              value: "mongodb://root:$(SECRET_PASS)@rocketchat-mongo-0.rocketchat-mongo:27017/local?replicaSet=rs0&authSource=admin"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: rocketchat-uploads
