apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-test-pvc
  namespace: nfs-storage-test
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: mac-nfs
  resources:
    requests:
      storage: 10Gi
  volumeName: mac-nfs-downloads
